### ISSUE TITLE
pin version of SimPEG?

### ISSUE THREAD

**Issue by lheagy** [simpeg-research/Herring-2021-Hybrid-ERT-Inversion#1]
This looks great Teddi! One quick suggestion for the environment file -- it might be worth specifying the version of SimPEG that you are using so that if there are changes in the future that would break things, it is clear where folks would need to go back to in order to run the code  

You can check your version of SimPEG by running 
```
import SimPEG
print(SimPEG.__version__)
```

**Comment by teddiherring** [comment]
Done! Thanks for the suggestion.
